package appserver

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
)

// GenerateJSONSchema derives the public request/response bundle from the Go
// protocol registry. External runtime payloads remain intentionally opaque.
func GenerateJSONSchema() ([]byte, error) {
	definitions := map[string]any{}
	methods := map[string]any{}
	notifications := map[string]any{}
	for _, method := range ProtocolMethods() {
		params := reflect.TypeOf(method.Params)
		result := reflect.TypeOf(method.Result)
		collectSchemaType(params, definitions)
		collectSchemaType(result, definitions)
		methods[method.Method] = map[string]any{
			"params": map[string]any{"$ref": "#/definitions/" + params.Name()},
			"result": map[string]any{"$ref": "#/definitions/" + result.Name()},
		}
	}
	for _, notification := range ProtocolNotifications() {
		params := reflect.TypeOf(notification.Params)
		collectSchemaType(params, definitions)
		notifications[notification.Method] = map[string]any{"params": map[string]any{"$ref": "#/definitions/" + params.Name()}}
	}
	bundle := map[string]any{
		"$schema":       "https://json-schema.org/draft/2020-12/schema",
		"title":         "Kepler App Server Protocol",
		"version":       ProtocolVersion,
		"methods":       methods,
		"notifications": notifications,
		"definitions":   definitions,
	}
	return json.MarshalIndent(bundle, "", "  ")
}

func collectSchemaType(value reflect.Type, definitions map[string]any) {
	value = dereference(value)
	if value.PkgPath() != reflect.TypeOf(InitializeParams{}).PkgPath() || value.Kind() != reflect.Struct || value.Name() == "" {
		return
	}
	if _, exists := definitions[value.Name()]; exists {
		return
	}
	definitions[value.Name()] = map[string]any{}
	properties := map[string]any{}
	required := []string{}
	for i := 0; i < value.NumField(); i++ {
		field := value.Field(i)
		name, optional := jsonField(field)
		if name == "" {
			continue
		}
		properties[name] = schemaFor(field.Type, definitions)
		if !optional {
			required = append(required, name)
		}
	}
	schema := map[string]any{"type": "object", "additionalProperties": false, "properties": properties}
	if len(required) > 0 {
		schema["required"] = required
	}
	definitions[value.Name()] = schema
}

func schemaFor(value reflect.Type, definitions map[string]any) any {
	value = dereference(value)
	localPackage := reflect.TypeOf(InitializeParams{}).PkgPath()
	if value.PkgPath() == localPackage && value.Kind() == reflect.Struct && value.Name() != "" {
		collectSchemaType(value, definitions)
		return map[string]any{"$ref": "#/definitions/" + value.Name()}
	}
	switch value.Kind() {
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.Slice, reflect.Array:
		if value == reflect.TypeOf(json.RawMessage{}) {
			return map[string]any{}
		}
		return map[string]any{"type": "array", "items": schemaFor(value.Elem(), definitions)}
	case reflect.Map, reflect.Interface, reflect.Struct:
		return map[string]any{}
	default:
		return map[string]any{}
	}
}

// GenerateTypeScript emits the protocol method map consumed by the CLI. It is
// generated from ProtocolMethods; clients never maintain a second method list.
func GenerateTypeScript() []byte {
	types := map[string]reflect.Type{}
	for _, method := range ProtocolMethods() {
		collectTSType(reflect.TypeOf(method.Params), types)
		collectTSType(reflect.TypeOf(method.Result), types)
	}
	for _, notification := range ProtocolNotifications() {
		collectTSType(reflect.TypeOf(notification.Params), types)
	}
	names := make([]string, 0, len(types))
	for name := range types {
		names = append(names, name)
	}
	sort.Strings(names)
	var out strings.Builder
	out.WriteString("// Code generated by appserver/cmd/protocolgen; DO NOT EDIT.\n\n")
	for _, name := range names {
		value := types[name]
		fmt.Fprintf(&out, "export type %s = {\n", name)
		for i := 0; i < value.NumField(); i++ {
			field := value.Field(i)
			jsonName, optional := jsonField(field)
			if jsonName == "" {
				continue
			}
			marker := ""
			if optional {
				marker = "?"
			}
			fmt.Fprintf(&out, "  %s%s: %s;\n", jsonName, marker, tsType(field.Type, types))
		}
		out.WriteString("};\n\n")
	}
	out.WriteString("export type ProtocolMethod =\n")
	for index, method := range ProtocolMethods() {
		separator := " |"
		if index == len(ProtocolMethods())-1 {
			separator = ";"
		}
		fmt.Fprintf(&out, "  %q%s\n", method.Method, separator)
	}
	out.WriteString("\nexport type ProtocolParams = {\n")
	for _, method := range ProtocolMethods() {
		fmt.Fprintf(&out, "  %q: %s;\n", method.Method, reflect.TypeOf(method.Params).Name())
	}
	out.WriteString("};\n\nexport type ProtocolResults = {\n")
	for _, method := range ProtocolMethods() {
		fmt.Fprintf(&out, "  %q: %s;\n", method.Method, reflect.TypeOf(method.Result).Name())
	}
	out.WriteString("};\n")
	out.WriteString("\nexport type NotificationMethod =\n")
	for index, notification := range ProtocolNotifications() {
		separator := " |"
		if index == len(ProtocolNotifications())-1 {
			separator = ";"
		}
		fmt.Fprintf(&out, "  %q%s\n", notification.Method, separator)
	}
	out.WriteString("\nexport type NotificationParams = {\n")
	for _, notification := range ProtocolNotifications() {
		fmt.Fprintf(&out, "  %q: %s;\n", notification.Method, reflect.TypeOf(notification.Params).Name())
	}
	out.WriteString("};\n")
	return []byte(out.String())
}

func collectTSType(value reflect.Type, types map[string]reflect.Type) {
	value = dereference(value)
	if value.Kind() == reflect.Slice || value.Kind() == reflect.Array {
		collectTSType(value.Elem(), types)
		return
	}
	if value.PkgPath() != reflect.TypeOf(InitializeParams{}).PkgPath() || value.Kind() != reflect.Struct || value.Name() == "" {
		return
	}
	if _, exists := types[value.Name()]; exists {
		return
	}
	types[value.Name()] = value
	for i := 0; i < value.NumField(); i++ {
		collectTSType(value.Field(i).Type, types)
	}
}

func tsType(value reflect.Type, types map[string]reflect.Type) string {
	value = dereference(value)
	if _, ok := types[value.Name()]; ok && value.PkgPath() == reflect.TypeOf(InitializeParams{}).PkgPath() {
		return value.Name()
	}
	switch value.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		if value == reflect.TypeOf(json.RawMessage{}) {
			return "unknown"
		}
		return "Array<" + tsType(value.Elem(), types) + ">"
	case reflect.Map:
		return "Record<string, unknown>"
	default:
		return "unknown"
	}
}

func dereference(value reflect.Type) reflect.Type {
	for value.Kind() == reflect.Pointer {
		value = value.Elem()
	}
	return value
}

func jsonField(field reflect.StructField) (string, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", true
	}
	parts := strings.Split(tag, ",")
	name := parts[0]
	if name == "" {
		name = field.Name
	}
	optional := false
	for _, option := range parts[1:] {
		optional = optional || option == "omitempty"
	}
	return name, optional
}
